package Preguntas;


import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AlumnosET20
 */
public class Pregunta14 extends javax.swing.JFrame {

    /**
     * Creates new form Pregunta14
     */
    public Pregunta14() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/historizz-logo.png"));
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Text_Pregunta = new javax.swing.JLabel();
        Pregunta = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Boton_Opcion1 = new javax.swing.JButton();
        Boton_Opcion2 = new javax.swing.JButton();
        Boton_Opcion3 = new javax.swing.JButton();
        imgPregunta = new javax.swing.JLabel();
        iconA = new javax.swing.JLabel();
        iconB = new javax.swing.JLabel();
        iconC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historizz - Pregunta 14");

        jPanel1.setBackground(new java.awt.Color(201, 237, 247));

        Text_Pregunta.setFont(new java.awt.Font("Cascadia Code", 1, 24)); // NOI18N
        Text_Pregunta.setText("Pregunta 14");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jTextArea1.setRows(1);
        jTextArea1.setText("¿Qué acontecimiento histórico tuvo lugar en\nArgentina el 17 de octubre de 1945?");
        jTextArea1.setFocusable(false);
        Pregunta.setViewportView(jTextArea1);

        Boton_Opcion1.setBackground(new java.awt.Color(204, 204, 204));
        Boton_Opcion1.setText("La nacionalización del petróleo");
        Boton_Opcion1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Boton_Opcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Opcion1ActionPerformed(evt);
            }
        });

        Boton_Opcion2.setBackground(new java.awt.Color(204, 204, 204));
        Boton_Opcion2.setText("El Día de la Lealtad");
        Boton_Opcion2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Boton_Opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Opcion2ActionPerformed(evt);
            }
        });

        Boton_Opcion3.setBackground(new java.awt.Color(204, 204, 204));
        Boton_Opcion3.setText("La Revolución del Parque");
        Boton_Opcion3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Boton_Opcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Opcion3ActionPerformed(evt);
            }
        });

        imgPregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/movimiento.png"))); // NOI18N
        imgPregunta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        iconA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imgPreguntas/Opciones/iconA.png"))); // NOI18N

        iconB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imgPreguntas/Opciones/iconB.png"))); // NOI18N

        iconC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imgPreguntas/Opciones/iconC.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(Text_Pregunta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(imgPregunta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconB)
                            .addComponent(iconA)
                            .addComponent(iconC))
                        .addGap(28, 28, 28)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton_Opcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Opcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Opcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(Pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconA)
                    .addComponent(Boton_Opcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconB)
                    .addComponent(Boton_Opcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconC, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Boton_Opcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(Text_Pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(imgPregunta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_Opcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Opcion1ActionPerformed
        JOptionPane.showMessageDialog(this, "Investigá más sobre el hecho ocurrido en 1945", "Incorrecto", JOptionPane.WARNING_MESSAGE);
        Puntuacion.respuestasIncorrectas++;
        Pregunta15 newframe = new Pregunta15();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Boton_Opcion1ActionPerformed

    private void Boton_Opcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Opcion2ActionPerformed
        JOptionPane.showMessageDialog(this, "Respuesta Correcta", "Correcto",JOptionPane.PLAIN_MESSAGE);
        Puntuacion.respuestasCorrectas++;
        Pregunta15 newframe = new Pregunta15();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Boton_Opcion2ActionPerformed

    private void Boton_Opcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Opcion3ActionPerformed
        JOptionPane.showMessageDialog(this, "Investigá más sobre el hecho ocurrido en 1945", "Incorrecto", JOptionPane.WARNING_MESSAGE);
        Puntuacion.respuestasIncorrectas++;
        Pregunta15 newframe = new Pregunta15();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Boton_Opcion3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pregunta14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pregunta14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pregunta14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pregunta14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pregunta14().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Opcion1;
    private javax.swing.JButton Boton_Opcion2;
    private javax.swing.JButton Boton_Opcion3;
    private javax.swing.JScrollPane Pregunta;
    private javax.swing.JLabel Text_Pregunta;
    private javax.swing.JLabel iconA;
    private javax.swing.JLabel iconB;
    private javax.swing.JLabel iconC;
    private javax.swing.JLabel imgPregunta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
