package MenuPrincipal;

import Preguntas.Pregunta1;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/historizz-logo.png"));
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo_Menu = new javax.swing.JLabel();
        Icono_Menu = new javax.swing.JLabel();
        BotonJugar_Menu = new javax.swing.JButton();
        icono_jugar = new javax.swing.JLabel();
        BotonAyuda_Menu = new javax.swing.JButton();
        icono_ayuda = new javax.swing.JLabel();
        BotonCreditos_Menu = new javax.swing.JButton();
        icono_creditos = new javax.swing.JLabel();
        BotonSalir_Menu = new javax.swing.JButton();
        icono_salir = new javax.swing.JLabel();
        banderaM = new javax.swing.JLabel();
        CR1 = new javax.swing.JLabel();
        CR2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historizz - Pantalla Principal");

        jPanel1.setBackground(new java.awt.Color(201, 237, 247));

        Titulo_Menu.setFont(new java.awt.Font("Cascadia Code", 1, 24)); // NOI18N
        Titulo_Menu.setText("Historizz");

        Icono_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historizz--logo(150x150).png"))); // NOI18N

        BotonJugar_Menu.setBackground(new java.awt.Color(204, 204, 204));
        BotonJugar_Menu.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotonJugar_Menu.setText("Jugar");
        BotonJugar_Menu.setBorder(null);
        BotonJugar_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugar_MenuActionPerformed(evt);
            }
        });

        icono_jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_jugar.png"))); // NOI18N

        BotonAyuda_Menu.setBackground(new java.awt.Color(204, 204, 204));
        BotonAyuda_Menu.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotonAyuda_Menu.setText("Ayuda");
        BotonAyuda_Menu.setBorder(null);
        BotonAyuda_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAyuda_MenuActionPerformed(evt);
            }
        });

        icono_ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_ayuda.png"))); // NOI18N

        BotonCreditos_Menu.setBackground(new java.awt.Color(204, 204, 204));
        BotonCreditos_Menu.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotonCreditos_Menu.setText("Créditos");
        BotonCreditos_Menu.setBorder(null);
        BotonCreditos_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCreditos_MenuActionPerformed(evt);
            }
        });

        icono_creditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_creditos.png"))); // NOI18N

        BotonSalir_Menu.setBackground(new java.awt.Color(204, 204, 204));
        BotonSalir_Menu.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BotonSalir_Menu.setText("Salir");
        BotonSalir_Menu.setBorder(null);
        BotonSalir_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalir_MenuActionPerformed(evt);
            }
        });

        icono_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_salir.png"))); // NOI18N

        banderaM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banderaM.jpg"))); // NOI18N

        CR1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        CR1.setText("Lautaro Blanco | Escuela Técnica ET 20 de 20");

        CR2.setText("Copyright© 2024");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(Icono_Menu))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(icono_creditos)
                                .addGap(18, 18, 18)
                                .addComponent(BotonCreditos_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(icono_jugar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonJugar_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(icono_ayuda)
                                    .addComponent(icono_salir))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonSalir_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonAyuda_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(Titulo_Menu))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(banderaM)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(Titulo_Menu)
                                .addGap(109, 109, 109)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(icono_ayuda)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(BotonAyuda_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Icono_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(icono_jugar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(BotonJugar_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(icono_creditos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(BotonSalir_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(BotonCreditos_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(icono_salir)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(banderaM))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CR1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CR2)))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalir_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalir_MenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalir_MenuActionPerformed

    private void BotonJugar_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugar_MenuActionPerformed
        Pregunta1 newframe = new Pregunta1();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonJugar_MenuActionPerformed

    private void BotonAyuda_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAyuda_MenuActionPerformed
        Pantalla_Ayuda newframe = new Pantalla_Ayuda();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonAyuda_MenuActionPerformed

    private void BotonCreditos_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCreditos_MenuActionPerformed
        Creditos newframe = new Creditos();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonCreditos_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAyuda_Menu;
    private javax.swing.JButton BotonCreditos_Menu;
    private javax.swing.JButton BotonJugar_Menu;
    private javax.swing.JButton BotonSalir_Menu;
    private javax.swing.JLabel CR1;
    private javax.swing.JLabel CR2;
    private javax.swing.JLabel Icono_Menu;
    private javax.swing.JLabel Titulo_Menu;
    private javax.swing.JLabel banderaM;
    private javax.swing.JLabel icono_ayuda;
    private javax.swing.JLabel icono_creditos;
    private javax.swing.JLabel icono_jugar;
    private javax.swing.JLabel icono_salir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
